In [1]:
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
print(codes)

[36, 162, 163, 165, 8364, 164]


In [2]:
codes = [ord(symbol) for symbol in symbols]
print(codes)

[36, 162, 163, 165, 8364, 164]


In [3]:
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print(beyond_ascii)

[162, 163, 165, 8364, 164]


In [4]:
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
print(beyond_ascii)

[162, 163, 165, 8364, 164]


In [8]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
print(tshirts)
print(tshirts[0])

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')


In [9]:
a, b, *rest = range(5)
print(a, b, rest)

0 1 [2, 3, 4]


In [10]:
a, *body, c, d = range(5)
print(a, body, c, d)

0 [1, 2] 3 4


In [11]:
*head, b, c, d = range(10)
print(head, b, c, d)

[0, 1, 2, 3, 4, 5, 6] 7 8 9


In [15]:
from collections import namedtuple
City = namedtuple('City', 'name country population cordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
print(tokyo)
print(tokyo.population)

City._fields

City(name='Tokyo', country='JP', population=36.933, cordinates=(35.689722, 139.691667))
36.933


('name', 'country', 'population', 'cordinates')

In [16]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [18]:
l[2:5] = [20,30]
l

[0, 1, 20, 30, 6, 7, 8, 9]

In [19]:
del l[5:7]
l

[0, 1, 20, 30, 6, 9]

In [20]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [21]:
'abcd' * 5

'abcdabcdabcdabcdabcd'

In [26]:
board = [['_'] for i in range(3)]
board

[['_'], ['_'], ['_']]

In [29]:
l = [i for i in range(10)]
h, *_, t = l
print(h, t)

0 9


In [38]:
a = [['_']*3]*3
a[1][2] = '0'
a

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [41]:
b = [['_' for i in range(3)] for j in range(3)]
b[1][2] = '0'
b

[['_', '_', '_'], ['_', '_', '0'], ['_', '_', '_']]

In [42]:
a = 6
id(a)

94001485157504

In [43]:
a += 6
id(a)

94001485157696

In [46]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))

        bisect_fn = bisect.bisect

print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect.bisect)

haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [52]:
breakpoints = [60, 70, 80, 90]
grades='FDCBA'
for i in [65, 70, 88, 90, 33]:
    pos = bisect.bisect(breakpoints, i)
    print(pos, grades[pos])

1 D
2 C
3 B
4 A
0 F


In [53]:
import random

SIZE = 7
random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [2]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
print(floats[-1])
with open('floats.bin', 'wb') as fp:
    floats.tofile(fp)

floats2 = array('d')
with open('floats.bin', 'rb') as fp:
    floats2.fromfile(fp, 10**7)
print(floats2[-1])

0.1303583216620493
0.1303583216620493


In [6]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)
memv_oct = memv.cast('B')
len(memv_oct)
print(memv_oct.tolist())

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]


In [20]:
import numpy as np12
a = np.arange(12)
a.shape = 3, 4
print(a)
print(a[:, 1])
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [23]:
a = [1,2,3,4,5]
a.append(6)
a
print(a.pop())

6


In [24]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
dq.extend([10,11,12])
dq

deque([3, 4, 5, 6, 7, 8, 9, 10, 11, 12])